export const COMPRESS_LEVEL_PRESETS = {
    light: {
        level: 'light',
        label: '轻度压缩',
        description: '几乎无损，适合高保真存档',
        quality: 90,
        resizeRatio: 1,
        pngCompressionLevel: 3,
        webpEffort: 2,
    },
    standard: {
        level: 'standard',
        label: '标准压缩',
        description: '画质与体积均衡，推荐日常使用',
        quality: 75,
        resizeRatio: 1,
        pngCompressionLevel: 6,
        webpEffort: 4,
    },
    high: {
        level: 'high',
        label: '较强压缩',
        description: '体积明显减小，适合网页展示',
        quality: 60,
        resizeRatio: 1,
        pngCompressionLevel: 7,
        webpEffort: 5,
    },
    aggressive: {
        level: 'aggressive',
        label: '强力压缩',
        description: '大幅缩小，尺寸缩放至 80%，适合移动端或缩略图',
        quality: 40,
        resizeRatio: 0.8,
        pngCompressionLevel: 8,
        webpEffort: 6,
    },
    extreme: {
        level: 'extreme',
        label: '极限压缩',
        description: '最大程度压缩，尺寸缩放至 60%，画质有明显损失',
        quality: 20,
        resizeRatio: 0.6,
        pngCompressionLevel: 9,
        webpEffort: 6,
    },
};
